### ISSUE TITLE
Histogram function broken for Cuda, OpenCL

### ISSUE THREAD

**Issue by rggjan** [arrayfire/arrayfire#1010]
When running the following code on Windows with ArrayFire v3.1.1, the results are completely broken for Cuda and somewhat broken for OpenCL (assuming the CPU version is correct), unless line 22 is uncommented (which should not change the results):

	#include <arrayfire.h>
	
	#include <cstdint>
	
	int main() {
	    af::array image = af::readArray("C:/Users/rggjan/tmp/image.raw", "test2");
	    af::array depth = af::readArray("C:/Users/rggjan/tmp/array.raw", "test");
	
	    af::array segmentation = af::abs(depth - 587) < 100;
	
	    int x = 771;
	    int y = 351;
	    int w = 426;
	    int h = 429;
	
	    af::array face_mask = segmentation(af::seq(x, x+w-1),
					       af::seq(y, y+h-1), 0);
	
	
	    af::array face_Y = image(af::seq(y, y+h-1), 0);
	
	    // face_mask = face_mask.as(f32); // Line 22: Uncomment me to get correct results on OpenCL
	
	    af::array hist_vector = face_Y(af::where(face_mask));
	    af::array histogram = af::histogram(af::flat(hist_vector), 256, 0, 255);
	
	    af_print(histogram);
	
	  return 0;
	}
	
The results I get are listed here:
https://drive.google.com/open?id=1Nc20pkUxgxw46TeQFHcSk6yQlvd23LUM82r4-y3tjuU

Notice that
  - CPU gives consistent results, no matter if line 22 is commented or not
  - CUDA gives consistent results as well, but different ones
  - OpenCL gives the same results as the CPU version, but only with line 22 uncommented. With line 22 commented, OpenCL gives completely unreasonable results (all values in one bin).

I was not able to reduce the problem further and still get the same results, so I assume that it has something to do with the JIT compiler combining the operations wrongly.

The input files can be downloaded here:
https://drive.google.com/folderview?id=0B0mZY8Aj3NgwVFRyalNkVC1uNlk&usp=sharing

**Comment by pavanky** [comment]
@rggjan Thanks for reporting this. This is a bug caused by indexing of segmentation. This is an easy fix.

**Comment by 9prady9** [comment]
@rggjan 
* Your CPU results are consistent with what i am seeing on my end.
* CUDA & OpenCL backend - i guess what @pavanky suggested might fix this.

@pavanky 
However, when i tried histogram on an image, i noticed the following behavior. All backends are producing consistent results for integral data types, however they differ from the results of float, double (results of float & double are matching though).

**Comment by pavanky** [comment]
@9prady9 Histogram in CUDA and OpenCL is not using offsets properly.

**Comment by 9prady9** [comment]
Never mind guys, i did a mistake in the test code stub, was using same floating point array as `.as(s32)` and comparing the results with integral type's results. Hence the discrepancy. There is no issue with histogram function on any backend.

**Comment by pavanky** [comment]
@rggjan This is fixed in the hotfixes-3.1.2 branch. The fix will come to devel later this week.

**Comment by rggjan** [comment]
I just downloaded and installed the new Release 3.1.2.

Unfortunately, I still see exactly the same results when running it (both for CUDA and for OpenCL wrong results).

Did I miss something?

**Comment by pavanky** [comment]
@rggjan can you print the output of af::info()?

**Comment by rggjan** [comment]
There you go:

    Device[1] has no support for OpenGL Interoperation
    ArrayFire v3.1.2 (OpenCL, 64-bit Windows, build 77128bb)
    [0] NVIDIA  : GeForce GTX 980 
    -1- INTEL   : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by 9prady9** [comment]
I think i narrowed it down to where the issue is - doesn't seem like histogram is the culprit. It is in the following line
```
af::array hist_vector = face_Y(af::where(face_mask));
```
When I split it as following
```
af::array test_       = af::where(face_mask);
af::array hist_vector = face_Y(test_);
```
There was no difference on the output of `test_ ` variable. However, `hist_vector` has different values on `cuda` and `cpu` backends. Interestingly, this difference beings much earlier in case of `opencl`, the result of `where` function itself differs in `opencl` backend.

**Comment by rggjan** [comment]
Interesting findings, thanks for digging into this.

I tried making the test case as simple as possible, to make it easier to debug (the actual code I use is much more complicated). However, I can imagine it is still hard to pinpoint the problem, since the input data is quite big.

**Comment by 9prady9** [comment]
@rggjan Is this still an issue with latest devel ?

**Comment by pavanky** [comment]
@9prady9 I don't think we fixed the issue.

**Comment by 9prady9** [comment]
@rggjan OpenCL backend has been fixed by @pavanky . We shall update here once the CUDA backend  has also been fixed.

**Comment by rggjan** [comment]
Sounds great, thanks for the progress so far!

**Comment by pavanky** [comment]
@rggjan While there is something wrong with CUDA backend with the existing code, shouldn't the following line:

```
 af::array face_Y = image(af::seq(y, y+h-1), 0);
```
be changed to

```
 af::array face_Y = image(af::seq(x, x+w-1), af::seq(y, y+h-1), 0);
```

**Comment by rggjan** [comment]
@pavanky Hmm... thats a good point, I didn't notice it before. In my code it is correct, when I wrote this test example code I seemed to do a mistake.

Maybe the current version even does something illegal?

**Comment by pavanky** [comment]
@rggjan The code in the issue creates out of bounds accesses. However that behavior should be the same for all backends. I am trying to figure out why CUDA backend is giving different results.

Anyway, thanks to the typo, we found and fixed a bunch of corner cases in ArrayFire :D 

Can you check if the proper code is working with the latest devel ?

**Comment by rggjan** [comment]
@pavanky  I can't test my code right now, but I will test it and tell you if its fixed as soon as possible.

Does the code give the same results for cuda, opencl and cpu if you change the line to include af::seq(x, x+w-1)?

**Comment by pavanky** [comment]
@rggjan Yes.

**Comment by pavanky** [comment]
I have narrowed down the remaining issue to this ticket: https://github.com/arrayfire/arrayfire/issues/1092

I am closing this issue since everything else seems to be fixed.
