### ISSUE TITLE
Feature Request: Basic Statistics fuctions

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire#12]
- mean
- standard deviation
- variance
- co-variance
- median
- correlation coefficient

**Comment by nathanjackson** [comment]
I have begun working on the variance.  @9prady9 I have am currently writing my own (currently CUDA, later OpenCL) kernels for variance .  Is there a better way to do this and get the same performance?

**Comment by 9prady9** [comment]
@nathanjackson cool, i just returned from vacation and ll start on standard deviation.
Please use the [same API](http://www.arrayfire.com/docs/group__core__func__cpp__var.htm) as ArrayFire 2.1 for variance function. This ll avoid breaking the API. 

Use element wise operations and existing functions(similar to the way we implemented mean) as much as possible. Unless a kernel written from scratch is giving significant performance improvement, it is better to reuse already written functions and element wise operations(JIT capabilities).

**Comment by nathanjackson** [comment]
Okay I'm about done with the variance over an entire array but I am running into a JIT compilation issue with the CUDA and OpenCL backends.  My tests pass the CPU version and the OpenCL and CUDA backends do compile, but they fail at runtime on the complex float\double types.  Any ideas? I'll post the exact errors when I get access to my computer.

**Comment by 9prady9** [comment]
@nathanjackson not sure how is JIT is throwing error. Did you add instantiations for complex types ?

**Comment by nathanjackson** [comment]
Yes, should I commit my changes as is?

**Comment by 9prady9** [comment]
Sure commit it if it is compiling fine. I shall take a look at it.

**Comment by pavanky** [comment]
@nathanjackson merge the latest devel into your branch. This problem was fixed a couple of weeks ago.

**Comment by nathanjackson** [comment]
@pavanky Merging the latest devel didn't seem to fix the problem.

**Comment by 9prady9** [comment]
@nathanjackson i checked the code you pushed. It seems like one of the element wise operations you are using inside `var` implementation  doesn't have the necessary implementation for complex types. I can dig more into this and let you know as soon as possible. I am currently on vacation, hence the longer delays in my replies. Hopefully i ll get some time to look at it over this weekend. In mean time, you can take help from @pavanky if you need any quick help.

**Comment by 9prady9** [comment]
@nathanjackson I have fixed that issue you were facing and pushed the changes to statistics on my fork. I have also merged latest devel into it.

**Comment by nathanjackson** [comment]
Great, I've been a bit busy with school work.  I'll try to make some more progress over the next week.

**Comment by 9prady9** [comment]
Cool, no problem. Just an fyi, I have to finish this issue next week since it has been in my queue for more than usual, especially due to my vacation :p . I shall leave `var` to you as you have already started working on it. Please let me know if you have started working on anything else so that we don't duplicate our efforts.

Thanks :)

**Comment by 9prady9** [comment]
@nathanjackson on a second thought, would it be fine if i take over `var` ?

**Comment by nathanjackson** [comment]
Go for it. :+1:

**Comment by 9prady9** [comment]
@nathanjackson I am almost done with var, i noticed something very important in the C API you added for var. You were using reference `&` operator  which shouldn't be for C bindings. You may use it for C++ bindings however. Just wanted to update you on that.
