### ISSUE TITLE
Lapack tests fail if CBlast is used

### ISSUE THREAD

**Issue by fzimmermann89** [arrayfire/arrayfire#1963]
A couple of BLAS-related tests (e.g. cholesky_dense, solve_dense,inverse_dense and LU) fail on a GTX Titan using OpenCL if compiled with CLBlast on Windows. 
Cholesky_dense gives errors like "Matrix C's OpenCL buffer is too small" , so I added some printf debugging to ClBlast's TestMatrixC:
```     
printf("ld          == %d\n", ld);
printf("one         == %d\n", one);
printf("two         == %d\n", two);
printf("offset      == %d\n", offset);
printf("buffer.size == %d\n", buffer.GetSize());
printf("req size   == %d\n", required_size); 
```

and Arrayfire's gpu_blas_herk_func in magma_blast_cblast.h:
```
printf("triangle      == %d\n", triangle);
printf("transpose     == %d\n", a_transpose);
printf("n             == %d\n", n);
printf("k             == %d\n", k);
printf("a_buffer      == %d\n", a_buffer);
printf("a_offset      == %d\n", a_offset);
printf("a_ld          == %d\n", a_ld);
printf("c_buffer      == %d\n", c_buffer);
printf("c_offset      == %d\n", c_offset);
printf("c_ld          == %d\n", c_ld);'
```

with this, cholesky_dense_opencl produced the following output

[cholesky.txt](https://github.com/arrayfire/arrayfire/files/1383868/cholesky.txt)

I don't know if this is caused by an error in CLBlast (probably not, CLBlast's test all pass) or by the integration in arrayfire.

Maybe @CNugteren  could take a look at it?

[inverse_LU_solve.txt](https://github.com/arrayfire/arrayfire/files/1382098/inverse_LU_solve.txt)

**Comment by fzimmermann89** [comment]
Just looking at the cholesky-chase right know:
Might it be an issue that cublast::herk is called for double input instead of syrk? herk is expecting complex matrices A and C..
But this doesn't explain the numeric failure for complex input, neither does it explain the other failures

**Comment by CNugteren** [comment]
That's a lot of output, perhaps you should make it a gist to make this issue a bit more readable? Anyway, I just took out one of the use-cases (the first for which the C-matrix is too small):
```
[ RUN ] Cholesky/0.LowerLarge
triangle == 122
transpose == 111
n == 128
k == 128
a_buffer == 217021728
a_offset == 128
a_ld == 1000
c_buffer == 217021728
c_offset == 128128
c_ld == 1000
ld == 1000
one == 128
two == 128
offset == 128128
buffer.size == 4000768
req size == 4084096
unknown file: error: C++ exception with description "ArrayFire Exception (Internal error:998):
In function int __cdecl magma_potrf_gpu(magma_uplo_t,int,struct _cl_mem *,unsigned __int64,int,struct _cl_command_queue *,int *)
In file src\backend\opencl\magma\potrf.cpp:251
CLBlast Error (-1009): Matrix C's OpenCL buffer is too small

In function int __cdecl af::cholesky(class af::array &,const class af::array &,const bool)
In file src\api\cpp\lapack.cpp:86" thrown in the test body.
[ FAILED ] Cholesky/0.LowerLarge, where TypeParam = float (249 ms)
```

CLBlast checks the size of matrix C in the HERK routine as follows:
`required_size = (c_ld * (n - 1) + n + c_offset) * sizeof(T);`
Filling this in with the above data (assuming double-complex?) gives:
`(1000 * (128 - 1) + 128 + 128128) * 16 = 4084096`
And indeed, if ArrayFire allocated 4000768 bytes then that is indeed not sufficient. Not sure how that value is obtained.

According to [Intel's docs](https://software.intel.com/en-us/node/520777), MKL even requires a size of c_ld * n, which would result in 4098048 required bytes. So CLBlast is not over-requesting it seems.

**Comment by fzimmermann89** [comment]
Thank you for your reply, I think the problem lies between
https://github.com/arrayfire/arrayfire/blob/master/src/backend/opencl/cholesky.cpp,
https://github.com/arrayfire/arrayfire/blob/master/src/backend/opencl/magma/potrf.cpp and
https://github.com/arrayfire/arrayfire/blob/master/src/backend/opencl/magma/magma_blas_clblast.h

You wrote some of that code - do you remember or see how it is ensured that clblast get a matrix of complex double?
If I didn't miss anything, then a real matrix will be used if cholesky is called with a real matrix.
This would explain the buffer sizes.

For clbas there seems to be an "overwrite" of hekr<double> with syrk in https://github.com/arrayfire/arrayfire/blob/master/src/backend/opencl/magma/magma_blas_clblas.h#L71

**Comment by CNugteren** [comment]
Yes, that could well be the issue. I never understood what this overwrite of herk to syrk was, but now I get it. I'll try to reproduce the issue later today on my machine and I'll work on a fix.

**Comment by CNugteren** [comment]
I managed to implement something similar to what was done in the clBLAS back-end, but a bit more modern using template specialisations:
https://github.com/CNugteren/arrayfire/commit/ce9b124a1d8fdcdde6df76af37ff805780da58f7

However, afterwards, I still see [failing tests everywhere](https://gist.github.com/CNugteren/56121763e5b781ecd287c4784d9c2ebe), although I no longer see any errors from CLBlast about incompatible matrix sizes.

**Comment by fzimmermann89** [comment]
that's progress!
`inverse`, `lu`, `solve` all "numerically" fail on my system as well. Initially I thought that the size errors and the numerical differences might have the same underlying reason, unfortunately that's probably not the case. 
I am puzzled. Will you continue investigating?

**Comment by CNugteren** [comment]
Yes, I will continue to investigate (although I have some other things on my plate as well). Could it be that all the failing tests use CLBlast's TRMM or TRSM routines?

**Comment by fzimmermann89** [comment]
that's at least something those tests have in common

**Comment by CNugteren** [comment]
I have just run all the tests on an NVIDIA test system, and here are all those that fail:
```
The following tests FAILED:
         11 - backend_unified (Failed)
         27 - cholesky_dense_opencl (Failed)
         63 - fftconvolve_opencl (Failed)
        105 - inverse_dense_opencl (Failed)
        115 - lu_dense_opencl (Failed)
        126 - meanshift_cpu (Timeout)
        189 - solve_dense_opencl (Failed)
        207 - svd_dense_opencl (Failed)
```
I suppose not all failures are CLBlast related?

About TRMM/TRSM: That could well be the issue. I'm not an expert on triangular solvers, but I managed to get something working. However, the results are not correct for any input matrix, that's why I had to generate proper input for the tests. Perhaps there is still a minor bug in the CLBlast implementation which manifests itself only for particular input matrices? Or there is some numerical instability?

I'll investigate when I have more time (next week hopefully), but any help is appreciated.

**Comment by CNugteren** [comment]
I've made a pull request (#1973) since that should at least solve some things. Not sure if all issues are solved yet, probably not. I've tried to reproduce it on my development machine (with an Intel GPU), but I can't seem to get failing tests (for e.g. `solve_dense_opencl`), not even on master. Any hints what could be the difference between the earlier NVIDIA-based system I tested on?

**Comment by fzimmermann89** [comment]
I am just testing cholesky_dense_opencl as a preliminary test: This test fails on nvidia fermi and kepler with numerical errors, but passes on intel.

**Comment by pavanky** [comment]
@fzimmermann89 Intel very likely falls back to using CBLAS / MKL even for OpenCL. I don't think intel passing is a good indicator.

**Comment by fzimmermann89** [comment]
argh, yes, sorry. If I set the env AF_OPENCL_CPU_OFFLOAD=0, the test will fail. 

@CNugteren do the tests pass on your system with AF_OPENCL_CPU_OFFLOAD=0? 
(if not set, potrf etc. will run on the cpu instead of using clblast if run on intel)

**Comment by CNugteren** [comment]
Ah, OK, thanks. I will try that and then I'll start debugging the issues.

**Comment by fzimmermann89** [comment]
(Maybe) interesting observation:
solve produces wrong results if N>128 on clblast

```python
import arrayfire as af
af.set_backend("opencl")
af.set_device(0)
print(af.info_str())

print("N\terror")
for N in range(64,256,8):
    maxerr=0
    for i in range(200):
        ad=af.round(af.randn(N,N, dtype=af.Dtype.f64)*10)
        xd=af.randn(N,1,dtype=af.Dtype.f64)
        yd=af.matmul(ad,xd)
        sd=af.solve(ad,yd)
        maxerr=max(af.max(xd-sd),maxerr)
    print("%d\t%f" %(N,maxerr))
```


> N	error
> 64	0.000000
> 72	0.000000
> 80	0.000000
> 88	0.000000
> 96	0.000000
> 104	0.000000
> 112	0.000000
> 120	0.000000
> 128	0.000000
> 136	964.387687
> 144	1734.540390
> 152	26390.381455
> 160	1169.954438
> 168	39747.910980
> 176	9528.567613
> 184	938.746822
> 192	3582.620300
> 200	21102.066632
> 208	2123.762696
> 216	2721.396341
> 224	283884.578561
> 232	7215.386582
> 240	8081.705961
> 248	8304.345139

**Comment by CNugteren** [comment]
Thanks for those experiments! I've just increased the matrix size for testing in the CLBlast tests, and I indeed see issues with seriously failing TRSM tests. So most probably that's the source of the issue. I'll investigate that and report on progress.

By the way, still couldn't get the ArrayFire tests working properly on my development system, because I ran into a Beignet issue (https://bugs.freedesktop.org/show_bug.cgi?id=94463). But thanks for the `AF_OPENCL_CPU_OFFLOAD=0` suggestion, that was indeed what I was missing.

**Comment by CNugteren** [comment]
I've found a major bug in the TRSM routine: there were missing synchronisations in the host-code after each call to a GEMM routine. This was not discover before, because it doesn't always manifest itself, depending on the device and the problem size. This bug [is now fixed in CLBlast](https://github.com/CNugteren/CLBlast/commit/d49aae236eca2dddc3228791ec367cc0c9d3bc7e).

Hopefully this now also fixes the failing ArrayFire tests. Since I can't reproduce on my own development system (see previous message) I'm not able to test right now, but I will soon on another system.

**Comment by fzimmermann89** [comment]
Unfortunately my quick testing didn't reveal a change in the failed tests, I will take a closer look on the weekend. Too bad that you can't get the tests working :(

**Comment by CNugteren** [comment]
I've fixed a few more things:
* Reduced the block size to make numerical errors less likely [commit](https://github.com/CNugteren/CLBlast/commit/449577cf07ac79768555a947e7036ee674c108c5).
* Fixed a similar issue in TRSV as the one I discovered two days ago in TRSM [commit](https://github.com/CNugteren/CLBlast/commit/44f7fa628a42d1e928c7c1c3a1bfca5de37de276).
* Fixed a bug occurring when using the offset argument for the A matrix [commit](https://github.com/CNugteren/CLBlast/commit/fa6e5e67f585b77d34c3031c176de9a0f7904aa9).

Now on my system I can successfully run the CLBlast tests (was already OK before), but now also with the `-full_test` argument (testing a-offset argument), and now also with larger matrix sizes.

Hopefully this fixes the issue. I'll be able to test tomorrow on another system. I'll report on the status then.

**Comment by pavanky** [comment]
@CNugteren Why is the synchronization required ? Are you using multiple queues ?

**Comment by fzimmermann89** [comment]
Yeay, the tests pass! Thank you!

The only tests that still fail are the MultiGPU tests in test_blas as well as in test_threading:

```
[ RUN      ] MatrixMultiply/0.MultiGPUSquare_CPP
unknown file: error: C++ exception with description "ArrayFire Exception (Internal error:998):
In function class opencl::Array<float> __cdecl opencl::matmul<float>(const class opencl::Array<float> &,const class opencl::Array<float> &,af_mat_prop,af_mat_prop)
In file src\backend\opencl\blas.cpp:104
CLBlast Error (-42): CL_INVALID_BINARY


In function class af::array __cdecl af::matmul(const class af::array &,const class af::array &,const af_mat_prop,const af_mat_prop)
In file src\api\cpp\blas.cpp:20" thrown in the test body.
```

It seems like switching the opencl device within one programm doesn't work right.


@CNugteren : can you tag a new version of clblast after those fixes?

**Comment by CNugteren** [comment]
Good to hear that it works now! I've also verified on an NVIDIA system, the tests pass. The only two that fail are:
```
	 11 - backend_unified (Failed)
	126 - meanshift_cpu (Timeout)
```

> Why is the synchronization required ? Are you using multiple queues ?

No, not multiple queues, but I meant putting events in an event waiting list and waiting for the appropriate events.

> can you tag a new version of clblast after those fixes

Yes, I could tag it now, but perhaps I can make a new full release anyway? Let's wait a few more days for the pull request to be accepted and things to settle down (to make sure there's no other bugs discovered) and then I'll release CLBlast 1.2.0.

**Comment by fzimmermann89** [comment]
@CNugteren: Fantastic! But I think it would be nice if you could tag a version before your PR is accepted so that you can include the version change 
https://github.com/arrayfire/arrayfire/blob/42a99a76684b662e30c3d76c896069d820ca9a96/CMakeModules/build_CLBlast.cmake#L16

Do you have any insight regarding the  failure of the MultiGPU tests?
They fail at least on this system (Intel i5 Haswell)
[output-clinfo.txt](https://github.com/arrayfire/arrayfire/files/1424704/output-clinfo.txt)

If I build with clblas instead, the tests pass. If I build with clblast only the multigpu parts fail. All other tests pass on both opencl devices. The issue seems to be with switching the device insight one programm.
Does clblast cache compiled kernels? Is this cache global or device specific?

**Comment by CNugteren** [comment]
OK, I've created the `1.2.0_rc1` tag and I've added that to the #1973 pull request.

There's two levels of caching:
* At program level based on the OpenCL context and device ID
* At binary level based on the OpenCL device name
From your clinfo it seems like you have 2 platforms with the same device name, so perhaps that's what is going wrong. I haven't added the OpenCL context to the binary level, because it can actually be re-used with another context. However, probably not for another platform. Perhaps I should add the OpenCL platform to the binary cache to fix your issue?

**Comment by fzimmermann89** [comment]
That sounds reasonable to add. 
I don't know why all the Intel windows machines I have access to have two different intel opencl platforms...
 If you have a patch ready I can test it. Unfortunately I won't have the time the next weeks to try to implement it myself. 

Maybe this fix will make it in 1.2.0?  ;-)

**Comment by CNugteren** [comment]
I've just made a [small commit](https://github.com/CNugteren/CLBlast/commit/ac5a58cfe5d2fad1ef248c619ad68611dcabcfc7) to a new branch `binary_cache_platform_dependent`. Could you check it out and see if that solves the issue? Unfortunately I cannot test myself on such a system set-up.

**Comment by fzimmermann89** [comment]
Thank you, this solves all the Opencl issues on the systems I have access to!

I will leave this issue open until your changes are merged and arrayfire pulls in a fixed version of clblast

**Comment by CNugteren** [comment]
OK! I'm working towards an official v1.2.0 release which we can use for ArrayFire, I'm doing some testing right now. However I noticed that the [Jenkins automated tests](http://ci.arrayfire.org/view/Other/) fail in some cases because I can't find CMake: see for example [here](http://ci.arrayfire.org/view/Other/job/other/job/CLBlast-Windows-Intel/149/console). Would be great if that can be fixed before I release 1.2.0 if it's not too much effort (cc @mlloreda).

**Comment by umar456** [comment]
Hey @CNugteren, We have been moving to buildbot so I haven't been monitoring things on Jenkins. I have fixed that test. Let me know if there is anything else you want me to look at. I will probably eventually add your project to buildbot eventually but things are pretty hectic here now.

**Comment by CNugteren** [comment]
Thanks a lot @umar456! Does that also mean that the [other build](http://ci.arrayfire.org/view/Other/job/other/job/CLBlast-Windows-NVIDIA/107/console) with a similar error will work fine after I push, or do you have to fix that issue separately?

I also see that the two AMD systems are offline in Jenkins. Are they available in buildbot? Please take your time with everything and let me know if I can help, I'm very grateful you are offering the test systems for CLBlast!

@fzimmermann89 I expect to release v1.2.0 this week. I'll update the PR afterwards with the latest tag.

**Comment by umar456** [comment]
I just fixed the other build as well. Let me know if you had other issues.

**Comment by CNugteren** [comment]
@umar456: Thanks a lot :-)

I just released CLBlast 1.2.0. I've updated #1973 to build with that version, so all issues should be resolved once merged in.

**Comment by CNugteren** [comment]
#1973 is now merged in (thanks a lot!), so I think this issue is now resolved. Perhaps @fzimmermann89 can re-run the tests on the latest version to see if this is indeed the case?

**Comment by CNugteren** [comment]
@fzimmermann89 We could close this issue, right? I also just noted there is a big typo in the title, it should be `CLBlast` rather than `CBlast` ;-)

**Comment by fzimmermann89** [comment]
Oh, yes. I haven't had problems since your fixes and will close this issue.
